import { AgentNodeState, VerificationClaim } from '@/types';

export const INITIAL_AGENTS: AgentNodeState[] = [
  {
    id: 'llm',
    name: 'LLM Candidate Agent',
    description: 'Generates unverified raw response candidate text',
    status: 'idle',
    progress: 0,
    executionTimeMs: 0,
    logs: [],
    metrics: { tokensPerSec: 42, temperature: 0.2 },
  },
  {
    id: 'detector',
    name: 'Hallucination Detector',
    description: 'Extracts claims & scans for ambiguity and factual risk',
    status: 'idle',
    progress: 0,
    executionTimeMs: 0,
    logs: [],
    metrics: { claimsExtracted: 8, riskScore: 0.12 },
  },
  {
    id: 'verifier',
    name: 'Ground Truth Verifier',
    description: 'Cross-checks claims against 30+ web & DOI databases',
    status: 'idle',
    progress: 0,
    executionTimeMs: 0,
    logs: [],
    metrics: { sourcesChecked: 14, httpSuccessRate: '100%' },
  },
  {
    id: 'memory',
    name: 'Vector Memory Agent',
    description: 'Queries persistent vector graph for past consensus facts',
    status: 'idle',
    progress: 0,
    executionTimeMs: 0,
    logs: [],
    metrics: { vectorMatches: 5, cosineSimilarity: 0.94 },
  },
  {
    id: 'judge',
    name: 'Consensus Judge Agent',
    description: 'Calculates Bayesian truth score per claim & system confidence',
    status: 'idle',
    progress: 0,
    executionTimeMs: 0,
    logs: [],
    metrics: { confidenceScore: 98.4, errorClassification: 'None' },
  },
  {
    id: 'corrector',
    name: 'Diff Corrector Agent',
    description: 'Applies diff patches & injects inline verified citations',
    status: 'idle',
    progress: 0,
    executionTimeMs: 0,
    logs: [],
    metrics: { diffsApplied: 1, inlineCitations: 7 },
  },
];

export const MOCK_CLAIMS: VerificationClaim[] = [
  {
    id: 'claim-1',
    claimText: 'Canberra is the capital city of Australia.',
    status: 'verified',
    confidence: 99.8,
    evidenceUrl: 'https://en.wikipedia.org/wiki/Canberra',
    evidenceSnippet: 'Canberra is the capital city of Australia, founded following the selection of the location in 1908.',
  },
  {
    id: 'claim-2',
    claimText: 'Sydney is the largest city by population in Australia.',
    status: 'verified',
    confidence: 98.5,
    evidenceUrl: 'https://www.abs.gov.au',
    evidenceSnippet: 'Sydney has an estimated population of over 5.3 million residents as of recent census statistics.',
  },
  {
    id: 'claim-3',
    claimText: 'Melbourne was named the capital of Australia in 1927.',
    status: 'corrected',
    confidence: 94.2,
    originalText: 'Melbourne was named the capital of Australia in 1927.',
    correctedText: 'Melbourne served as the seat of government from 1901 until 1927 when Parliament moved to Canberra.',
    evidenceUrl: 'https://www.aph.gov.au',
    evidenceSnippet: 'The Federal Parliament was opened in Melbourne in 1901 and moved to Canberra in 1927.',
  },
];
